// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xifhvoqdrmsunijcrakv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZmh2b3Fkcm1zdW5pamNyYWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjMwMzYsImV4cCI6MjA2NDYzOTAzNn0.D9LOk7Q2rw8jhOh76mxNN_j8Bxtkx6wAcWCtzhQtVsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);